"""initial schema from DATA_MODEL.sql

Revision ID: 79333c6c4815
Revises: 
Create Date: 2026-09-15 22:49:47.093496
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '79333c6c4815'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Every UUID primary key defaults to gen_random_uuid(), which pgcrypto
    # provides. Must run before the first CREATE TABLE.
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('km_explanation', sa.Text(), nullable=False),
    sa.Column('common_l1_errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('hskk_task_types', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_concepts_level', 'concepts', ['language', 'level', 'sort_order'], unique=False)
    op.create_table('content_packs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('licence', sa.Text(), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('jsonb_array_length(sources) > 0', name='sources_not_empty'),
    sa.CheckConstraint('length(trim(licence)) > 0', name='licence_not_blank'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'level', 'version')
    )
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), server_default=sa.text("'standard'"), nullable=False),
    sa.Column('seats', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), server_default=sa.text("'km'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('concept_mastery',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('mastery_score', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ease_factor', sa.REAL(), server_default=sa.text('2.5'), nullable=False),
    sa.Column('interval_days', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('next_due_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'concept_id')
    )
    op.create_index('idx_mastery_due', 'concept_mastery', ['user_id', 'next_due_at', 'mastery_score'], unique=False)
    op.create_table('cost_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('quantity', sa.REAL(), nullable=False),
    sa.Column('cost_usd_cents_est', sa.Integer(), nullable=False),
    sa.Column('ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_time', 'cost_ledger', [sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('idx_cost_user_month', 'cost_ledger', ['user_id', 'occurred_at'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('course_type', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('title_km', sa.Text(), nullable=False),
    sa.Column('title_zh', sa.Text(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("course_type IN ('exam','job')", name='courses_course_type_check'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name='fk_courses_org', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_courses_lookup', 'courses', ['language', 'course_type', 'level'], unique=False)
    op.create_table('entitlements',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('realtime_seconds_remaining', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('daily_attempts_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('daily_tasks_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reset_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('realtime_seconds_remaining >= 0', name='realtime_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('experiments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experiment_key', sa.Text(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'experiment_key')
    )
    op.create_table('org_members',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_role', sa.Text(), nullable=True),
    sa.Column('enrolled_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'user_id')
    )
    op.create_table('org_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'period')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_ref', sa.Text(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('currency_minor_units', sa.SmallInteger(), server_default=sa.text('2'), nullable=False),
    sa.Column('is_recurring_charge', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('realtime_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('seconds_billed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_usd_cents_est', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('transcript_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rt_user_time', 'realtime_sessions', ['user_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('streaks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_day', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('renewal_mode', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('period_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('grace_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('payment_provider', sa.Text(), nullable=True),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('mandate_ref', sa.Text(), nullable=True),
    sa.Column('next_charge_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("plan IN ('free','basic','pro')", name='subscriptions_plan_check'),
    sa.CheckConstraint("renewal_mode <> 'auto' OR mandate_ref IS NOT NULL", name='auto_needs_mandate'),
    sa.CheckConstraint("renewal_mode IN ('auto','manual')", name='subscriptions_renewal_mode_check'),
    sa.CheckConstraint("status IN ('active','grace','expired','cancelled')", name='subscriptions_status_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sub_due_auto', 'subscriptions', ['next_charge_at'], unique=False, postgresql_where=sa.text("renewal_mode = 'auto' AND status = 'active'"))
    op.create_index('idx_sub_due_manual', 'subscriptions', ['period_end'], unique=False, postgresql_where=sa.text("renewal_mode = 'manual' AND status = 'active'"))
    op.create_index('idx_sub_user_active', 'subscriptions', ['user_id', 'status', sa.literal_column('period_end DESC')], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_language', sa.Text(), server_default=sa.text("'zh'"), nullable=False),
    sa.Column('current_level', sa.Text(), server_default=sa.text("'HSK1'"), nullable=False),
    sa.Column('daily_goal_minutes', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('timezone', sa.Text(), server_default=sa.text("'Asia/Phnom_Penh'"), nullable=False),
    sa.Column('data_saver', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('concept_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title_km', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'sequence')
    )
    op.create_table('lesson_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=True),
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('media_type', sa.Text(), server_default=sa.text("'audio'"), nullable=False),
    sa.Column('anchor', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.CheckConstraint("item_type IN ('explain','drill','vocab','qa')", name='lesson_items_item_type_check'),
    sa.CheckConstraint("media_type IN ('audio','video')", name='lesson_items_media_type_check'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'sequence')
    )
    op.create_table('lesson_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('started','completed')", name='lesson_progress_status_check'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'lesson_id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_item_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('asr_text', sa.Text(), nullable=True),
    sa.Column('pron_score', sa.REAL(), nullable=True),
    sa.Column('accuracy_score', sa.REAL(), nullable=True),
    sa.Column('fluency_score', sa.REAL(), nullable=True),
    sa.Column('completeness_score', sa.REAL(), nullable=True),
    sa.Column('prosody_score', sa.REAL(), nullable=True),
    sa.Column('tone_score', sa.REAL(), nullable=True),
    sa.Column('phoneme_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['lesson_item_id'], ['lesson_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attempts_concept', 'attempts', ['user_id', 'concept_id'], unique=False)
    op.create_index('idx_attempts_user_time', 'attempts', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lesson_item_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('source_text_hash', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('audio','video')", name='media_assets_kind_check'),
    sa.ForeignKeyConstraint(['lesson_item_id'], ['lesson_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_item_id', 'kind')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_assets')
    op.drop_index('idx_attempts_user_time', table_name='attempts')
    op.drop_index('idx_attempts_concept', table_name='attempts')
    op.drop_table('attempts')
    op.drop_table('lesson_progress')
    op.drop_table('lesson_items')
    op.drop_table('lessons')
    op.drop_table('user_profiles')
    op.drop_index('idx_sub_user_active', table_name='subscriptions')
    op.drop_index('idx_sub_due_manual', table_name='subscriptions', postgresql_where=sa.text("renewal_mode = 'manual' AND status = 'active'"))
    op.drop_index('idx_sub_due_auto', table_name='subscriptions', postgresql_where=sa.text("renewal_mode = 'auto' AND status = 'active'"))
    op.drop_table('subscriptions')
    op.drop_table('streaks')
    op.drop_index('idx_rt_user_time', table_name='realtime_sessions')
    op.drop_table('realtime_sessions')
    op.drop_table('payments')
    op.drop_table('org_reports')
    op.drop_table('org_members')
    op.drop_table('experiments')
    op.drop_table('entitlements')
    op.drop_index('idx_courses_lookup', table_name='courses')
    op.drop_table('courses')
    op.drop_index('idx_cost_user_month', table_name='cost_ledger')
    op.drop_index('idx_cost_time', table_name='cost_ledger')
    op.drop_table('cost_ledger')
    op.drop_index('idx_mastery_due', table_name='concept_mastery')
    op.drop_table('concept_mastery')
    op.drop_table('users')
    op.drop_table('orgs')
    op.drop_table('content_packs')
    op.drop_index('idx_concepts_level', table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###

    # pgcrypto is deliberately NOT dropped. We cannot tell whether this
    # migration created it or found it already present, and removing an
    # extension another schema depends on is worse than leaving an unused one.
